apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: proxmox
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 80
      targetPort: 8006
  selector: {}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: proxmox
  namespace: proxmox
  labels:
    kubernetes.io/service-name: proxmox
addressType: IPv4
ports:
  - name: https
    port: 8006
    protocol: TCP
endpoints:
  - addresses:
      - 192.168.68.75
    conditions:
      ready: true
