apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-ingressroute
  namespace: gitea
  annotations:
    meta.helm.sh/release-name: gitea
    meta.helm.sh/release-namespace: gitea
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`git.homelab.azuanz.com`)
      kind: Rule
      services:
        - name: gitea-http
          port: 3000
  tls:
    secretName: homelab-certificate-secret
